apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stock
  name: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  strategy: {}
  template:
    metadata:
      labels:
        app: stock
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "stock"
        dapr.io/app-port: "5000"
    spec:
      containers:
#      - image: <account-id>.dkr.ecr.<region>.amazonaws.com/stock-image:latest # for ECR
      - image: stock-image
        name: stock-image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stock
  name: stock
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: stock
  type: ClusterIP
status:
  loadBalancer: {}