apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  strategy: {}
  template:
    metadata:
      labels:
        app: payment
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "payment"
        dapr.io/app-port: "5000"
    spec:
      containers:
      - image: payment-image
        name: payment-image
        ports:
        - containerPort: 5000