apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  strategy: {}
  template:
    metadata:
      labels:
        app: order
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "order"
    spec:
      containers:
      - image: order-image
        name: order-image
        ports:
        - containerPort: 3000