apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: stock
build:
  artifacts:
  - image: stock-image
    context: ./
    docker:
      dockerfile: ./Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests: 
    - ./manifest/deployment.yaml
    - ./manifest/service.yaml